### PR TITLE
Updated Wyzeapy to be compatible with Wyze Sensors (old model)

### LINKED ISSUE #4: Wyzeapy time related code not transportable and get_event_list possibly have a design flaw
**Issue 1**
In `get_event_list()` in `base_client.py`, the following time functions is used:

`            "begin_time": int(str(datetime.date.today().strftime("%s")) + "000"),
`

`strftime("%s")` is not supported on Windows. For more info what is supported for [strftime()](url), see this [link](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?redirectedfrom=MSDN&view=msvc-160).

This results in the following error on Windows:
```
Traceback (most recent call last):

  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\wyzeapy\client.py", line 237, in get_latest_event
    raw_events = self.client.get_event_list(device, 10)['data']['event_list']
  File "C:\Users\-\AppData\Local\Programs\Python\Python39\lib\site-packages\wyzeapy\base_client.py", line 432, in get_event_list
    "begin_time": int(str(datetime.date.today().strftime("%s")) + "000"),

ValueError: Invalid format string
```

**Issue 2**
This method also has a built in flaw. Possible number of events differs depending of time-of-day. 1am will only provide 1hrs of possible hits, but 11pm will provide 23hrs of possible hits.

Propose to change to a function relative to now. Suppose 2hrs x 60 minutes x 60 seconds should be enough.
`            "begin_time": int(str(int(time.time() - (2 * 60 * 60))) + "000"),
`

This should fix both issue as time.time() is transportable, and the function now works as intended (?)

### PR DESCRIPTION
**Pull request by faanskit**
Updated Wyzeapy to be compatible with Wyze Sensors (old model).
And fixed #4

### CODE REVIEW

**Comment by faanskit** [comment]
Sample code for turning notifications on/off

These variants work
-  NOTIFICATIONS
-  MOTION_NOTIFICATION
-  SOUND_NOTIFICATION
 

```
from wyzeapy.base_client import AccessTokenError, DeviceTypes, Device, PropertyIDs, ActionNotSupported, Group, EventTypes
from wyzeapy.client import Client
import sys

if __name__ == '__main__':
    if len(sys.argv) == 2:
        wyze_client = Client("username", "password")
        devices = wyze_client.get_devices()
        for device in devices:
            device_type: DeviceTypes = DeviceTypes(device.product_type)
            if device_type == DeviceTypes.CAMERA:
                if sys.argv[1] == "off":
                    device_info = wyze_client.notifications_off(device, PropertyIDs.NOTIFICATIONS)
                elif sys.argv[1] == "on":
                    device_info = wyze_client.notifications_on(device, PropertyIDs.NOTIFICATIONS)
```

**Comment by JoshuaMulliken** [comment]
Hey @faanskit can you update this to fit the current project?

**Comment by faanskit** [comment]
> Hey @faanskit can you update this to fit the current project?

Sure, but it will take some time before I can do it. Do not have access to a dev enviroment for a few weeks and have not followed what changes has been made.

**Comment by JoshuaMulliken** [comment]
No worries! Whenever you get a chance

**Pull request closed without merging**
