### PR TITLE
Remove cchardet

### PR DESCRIPTION
**Pull request by brg468**
As discussed here https://github.com/JoshuaMulliken/wyzeapy/issues/66. and here https://github.com/JoshuaMulliken/ha-wyzeapi/issues/462

HA is blocking cchardet in release 2023.3 as it's unmaintained and doesn't support Python 3.11. It doesn't appear that its used in the code so this removes it as a dependency to fix the conflict.

### CODE REVIEW

**Comment by JoeSchubert** [comment]
LGTM. This should have no effects on the actual package other than removing cchardet as a listed dependent.

**Comment by debsahu** [comment]
I'm on HA 2023.3.0 and this might fix the broken add on in this version of HA. Could someone merge this after testing?

**Review by JoshuaMulliken — APPROVED** [review]
LGTM

**Comment by JoshuaMulliken** [comment]
I will get a version pushed once I am back in front of the computer

**Pull request merged**
